"""Adjusted the unicode length

Revision ID: 1a2790b8f66e
Revises: b498599c4e19
Create Date: 2025-02-02 14:05:25.534713

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a2790b8f66e"
down_revision: Union[str, None] = "b498599c4e19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "profile_image_url",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=150),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Unicode(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.Unicode(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.Unicode(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.Unicode(length=20),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "profile_image_url",
        existing_type=sa.Unicode(length=150),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.Unicode(length=32),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.Unicode(length=128),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.Unicode(length=320),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
