"""Fixed the last_login_at from default boolean to datetime

Revision ID: 1d26e1a8f9c2
Revises: a665fc076ae3
Create Date: 2025-02-02 17:29:34.805873

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d26e1a8f9c2"
down_revision: Union[str, None] = "a665fc076ae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
