"""made the created_by, updated_by column nullable

Revision ID: 9abcdb0b70d0
Revises: 1d26e1a8f9c2
Create Date: 2025-02-02 17:32:51.618983

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9abcdb0b70d0"
down_revision: Union[str, None] = "1d26e1a8f9c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("address", "created_by", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("address", "updated_by", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("users", "created_by", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("users", "updated_by", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "updated_by", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("users", "created_by", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("address", "updated_by", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("address", "created_by", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
