"""Added address table

Revision ID: d8bdde604dd1
Revises: 1a2790b8f66e
Create Date: 2025-02-02 14:31:41.594675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bdde604dd1'
down_revision: Union[str, None] = '1a2790b8f66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('street_address', sa.Unicode(length=255), nullable=False),
    sa.Column('city', sa.Unicode(length=100), nullable=False),
    sa.Column('state', sa.Unicode(length=100), nullable=False),
    sa.Column('zip_code', sa.Unicode(length=20), nullable=True),
    sa.Column('country', sa.Unicode(length=100), nullable=False),
    sa.Column('address_type', sa.Enum('BILLING', 'SHIPPING', 'HOME', 'WORK', 'WAREHOUSE', name='addresstype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
